export const ROUTE_PATHS = {
  home: "/",
  login: "/login",
  adminLogin: "/admin/login",
  register: "/register",
  adminDashboard: "/admin/dashboard",
  adminStudentProfiles: "/admin/student-profiles",
  adminModules: "/admin/modules",
  adminTimetable: "/admin/timetable",
  adminAcademicEvents: "/admin/academic-events",
  dashboard: "/dashboard",
  myModules: "/my-modules",
  myTimetable: "/my-timetable",
  myEvents: "/my-events",
  tasks: "/tasks",
e: "/admin/timetable",
  adminStudentGroups: "/admin/student-groups",
  adminAssignments: "/admin/assignments",
  adminPresentations: "/admin/presentations",
  adminViva: "/admin/viva",
  adminLabTests: "/admin/lab-tests",
  adminExams: "/admin/exams",
  dashboard: "/dashboard",
  tasks: "/tasks",
};
